### ISSUE TITLE
[Suggestion] Change boolean keyword

### ISSUE THREAD

**Issue by MathiasDPX** [Revxrsal/Lamp#102]
![image](https://github.com/user-attachments/assets/16ef54f8-466c-4b8c-8ec9-113631520cbf)
Be able to change true and false to anything, like allow, disallow

**Comment by MathiasDPX** [comment]
example:
![image](https://github.com/user-attachments/assets/43e305ad-f23c-49f9-8495-c3c6bbb41ae8)

**Comment by Revxrsal** [comment]
You can implement this yourself by registering a custom ValueResolverFactory for boolean parameters
