### ISSUE TITLE
Support Kotlin/Native for `cli`

### ISSUE THREAD

**Issue by gmitch215** [Revxrsal/Lamp#107]
Just re-discovered Lamp and noticed v4 is currently in progress.

I think it would be cool if Lamp supported Kotlin Multiplatform, specifically Kotlin/Native on the CLI portion so that CLI applications can be raw executables instead.

**Comment by Revxrsal** [comment]
Correct me if I'm wrong, but Kotlin Native does not bundle the JVM with it. Lamp is written entirely in Java and uses a lot of Java-specific APIs. I am not sure if this is possible, unfortunately.

**Comment by gmitch215** [comment]
That is correct. I forgot that you also have a `common` module written in Java.
