### ISSUE TITLE
[Lamp 4] Paper Async Tab Complete

### ISSUE THREAD

**Issue by FigT** [Revxrsal/Lamp#108]
### Problem
Often you'll need/want tab suggestions from a database, and with Lamp's current auto-complete system on Bukkit, these suggestions need to be provided synchronously on the main thread, where executing database queries is not a great idea.

### Solution
Paper offers support for tab-completion to be done asynchronously, both with and without Brigadier. It would be very helpful to integrate this into Lamp, especially with the v4 update changing a lot of internals anyway, it seems like the right time.

Thanks for reading!

**Comment by Revxrsal** [comment]
Added in Beta 11. Thanks for the suggestion.

**Comment by Revxrsal** [comment]
Figured out it may be useful to include a bit of information on the implementation:
- Asynchronous completion is enabled for everything _by default_ on Paper platforms
- For Brigadier, you will have to use `SuggestionProvider#fromAsync`. `fromAsync` takes an `AsyncSuggestionProvider`, which has a single  method: `CompletableFuture<Collection<String>> getSuggestionsAsync(@NotNull ExecutionContext<A> context)`.

**Comment by FigT** [comment]
Ooh awesome! 
_Thank you! It looks great_
