### ISSUE TITLE
[Enhancement] Kotlin Extensions for AutoCompleter

### ISSUE THREAD

**Issue by TehNeon** [Revxrsal/Lamp#11]
There are currently no extensions or additional functions for the AutoCompleter system. This currently results in having to write some pretty ugly looking code.

What the code looks like in Kotlin currently:
```kotlin
commandHandler.autoCompleter.registerParameterSuggestions(String::class.java) { args, sender, command ->
	emptyList<String>()
}
```

What it could look like in Kotlin (This example follows the current naming scheme of the extensions):
```kotlin
commandHandler.autoCompleter.parameterSuggestions<String> { args, sender, command ->
	emptyList<String>()
}
```

**Comment by Revxrsal** [comment]
Yes, auto-completer extensions should be implemented. Will get to this soon :)

**Comment by Revxrsal** [comment]
Added in https://github.com/Revxrsal/Lamp/commit/6eee6ccd6eca864b6d318d5f014f20cd465104ac.
