### ISSUE TITLE
[Lamp v4] Async Parameter Types

### ISSUE THREAD

**Issue by FigT** [Revxrsal/Lamp#112]
## Problem
Sometimes you'll need to get some data (POJO from an ORM for example) from a database, and you'll want this to be queried on a different thread, but to do this asynchronously in a command you'll need to use a normal parameter (string for a user's ID for example), and then query the DB in the command method, resulting in duplicated and tedious code, if you have lots of commands.

## Solution
Adding a method like `boolean isAsync()` to the `ParameterType` class, specifying if resolving the parameter/value is ran async (off of the main server thread in Minecraft's case) would be quite helpful.
<br/>
*sorry if I explained this poorly*

Cheers!

**Comment by Revxrsal** [comment]
Hm. What if it takes 10 seconds to resolve the value? Should the user receive no feedback until the async parameter is resolved?

I have a different design in mind, which may give you finer control over that.

**Comment by FigT** [comment]
Hmm, that's a good point. For most cases, I think it's not that big of a deal for a user to have no feedback until it's resolve, but I can definitely see people wanting that. 

Maybe allowing a CompletableFuture to be resolved/completed (async) could work? That way, a developer could add a timer and and send messages and such if they wanted to.

I'm curious what you had in mind though!

**Comment by Revxrsal** [comment]
That still brings up a few issues. Lamp relies on exceptions to know whether a command can parse certain input or not. Asynchronous parameters mean that this information will be unavailable until later.

Nonetheless, it’s possible to just create a ParameterType.Factory for all CompletableFuture classes that delegates the parsing logic to an asynchronous executor, while handing exceptions with Lamp#handleException.

Feel free to open a PR. I may give it a go later.
