### ISSUE TITLE
Suggestions of multi-word arguments are not displayed correctly when using flags

### ISSUE THREAD

**Issue by Grabsky** [Revxrsal/Lamp#116]
Just like in the title. Screenshots and notes below the code snippet.

**Version:** `4.0.0-beta.18`

Reproduction code:
```java
public final class LampTest extends JavaPlugin {

    private LampTest plugin;
    private Lamp<BukkitCommandActor> lamp;

    @Override
    public void onEnable() {
        this.plugin = this;
        // Disabling Brigadier integration...
        final BukkitLampConfig<BukkitCommandActor> config = BukkitLampConfig.builder(this).disableBrigadier().build();
        // Initializing Lamp...
        this.lamp = BukkitLamp.builder(config)
                .parameterTypes(it -> {
                    it.addParameterType(Location.class, LocationParameter.INSTANCE);
                })
                .suggestionProviders(it -> {
                    it.addProvider(Location.class, LocationParameter.INSTANCE);
                })
                .build();
        // Registering commands...
        lamp.register(TestCommand.INSTANCE);
    }

    private enum TestCommand {
        INSTANCE; // SINGLETON

        @Command("npc2 create")
        public void onCreate(
                final @NotNull Player sender,
                final @NotNull String name,
                final @Nullable @Flag("location") Location location,
                final @Nullable @Flag("type") EntityType type
        ) {
            final EntityType finalType = (type != null) ? type : EntityType.PLAYER;
            sender.sendMessage("Creating NPC named " + name + " and type " + finalType.name() + " at " + location.x() + ", " + location.y() + ", " + location.z());
        }

    }

    // NOTE: Just an example, '~' support is currently missing.
    private enum LocationParameter implements ParameterType<BukkitCommandActor, Location>, SuggestionProvider<BukkitCommandActor> {
        INSTANCE; // SINGLETON

        @Override
        public @Nullable Location parse(final @NotNull MutableStringStream stream, final @NotNull ExecutionContext<BukkitCommandActor> context) {
            final double x = stream.readDouble();
            final double y = stream.readDouble();
            final double z = stream.readDouble();
            // ...
            return new Location(context.actor().sender() instanceof Player sender ? sender.getWorld() : Bukkit.getWorlds().getFirst(), x, y, z);
        }

        @Override
        public @NotNull Collection<String> getSuggestions(final @NotNull ExecutionContext<BukkitCommandActor> context) {
            return List.of("~ ~ ~");
        }
    }

}
```

Initial completions are displayed as expected:
![image](https://github.com/user-attachments/assets/6c16bd0c-6609-471f-9db3-24ec9326ff05)
But when typign the second arguments, instead of suggesting the remaining `~ ~`, next flag appears.
![image](https://github.com/user-attachments/assets/32d4e640-624c-4954-b810-f4cdc4096f42)
Completions for the `--type` flag are suggested as they should be, given the previous argument is exactly one word. (Which makes it invalid for the parser)
![image](https://github.com/user-attachments/assets/8333969e-f4b3-4471-9761-f6286396489d)
When `--location` argument is filled properly, suggestions for the next flag are invalid. 
![image](https://github.com/user-attachments/assets/69ba35fd-8f41-4361-bea0-f9f66c1202ed)

I don't know how to explain it, hopefully you can see the problem. In any case, feel free to ask me and I'll try to answer as clear as possible.

I also attached compiled `.jar` file which works only on **Paper** (or forks) version **1.21.1** and **Java 21**. It's in the `.zip` archive as apparently `.jar` files cannot be uploaded directly.
[LampTest-1.0-SNAPSHOT.zip](https://github.com/user-attachments/files/17440552/LampTest-1.0-SNAPSHOT.zip)

**Comment by Revxrsal** [comment]
I think the issue is because of your problematic implementation of LocationParameterType. `MutableStringStream` does not consume spaces, you have to do that yourself.

Here's the correct implementation:
```java
@Override
public Location parse(@NotNull MutableStringStream input, @NotNull ExecutionContext<@NotNull BukkitCommandActor> context) {
    double x = input.readDouble();

    consumeSpace(input, "Expected 'y'.");
    double y = input.readDouble();

    consumeSpace(input, "Expected 'z'.");
    double z = input.readDouble();

    return new Location(context.actor().requirePlayer().getWorld(), x, y, z);
}

private static void consumeSpace(@NotNull MutableStringStream input, @NotNull String error) {
    if (input.hasFinished())
        throw new CommandErrorException(error);
    if (input.peek() == ' ')
        input.moveForward();
}
```
With this implementation, the auto-completion works fine for me:
![image](https://github.com/user-attachments/assets/4c53ae76-d3fd-4422-ae5e-6ce595fc0e46)
![image](https://github.com/user-attachments/assets/da8b3d12-01dc-4f75-961d-5f1b5fcb0fb0)
![image](https://github.com/user-attachments/assets/091bb200-2627-4c91-85f9-2508cd636e4b)
![image](https://github.com/user-attachments/assets/070e441e-0e7b-4ad6-b971-69b043289ab4)
The reason that the implementation matters, is that Lamp checks whether the parameter parser gives an error or not. If it does, it tries to find suitable suggestions that start with the input, as the it could be incomplete (e.g. part of a player name). Otherwise, it gives up and returns an empty list, then proceeds to give suggestions for following suggestions.

Can you try it and tell me if the issue continues?

**Comment by Grabsky** [comment]
Your solution seems to work, yes. I'll adjust it to work with `~` characters and it should behave as I'd like to. Thanks for pointing this out.

I do have question however, which might not be related to the title of the issue, but is still relevant to the problem.

Seeing how `SuggestionProvider#getSuggestions` works - it is called only once, for the first argument - how would I go about implementing something like this?

**1st**
Input: `/npc create test --location `
Suggestions: `~ ~ ~`

**2nd**
Input: `/npc create test --location ~ `
Suggestions: `~ ~`

**3rd**
Input: `/npc create test --location ~ ~ `
Suggestions: `~`

I was unable to get anything other than **1st** to work.

**Comment by Revxrsal** [comment]
If I'm not wrong, this is indeed what Lamp does. Have you tried it after supporting the `~` syntax?

**Comment by Grabsky** [comment]
> **@Revxrsal**: If I'm not wrong, this is indeed what Lamp does. Have you tried it after supporting the ~ syntax?

I tried with numbers and parser you sent in the snippet above. Does not seem to work unless I'm doing something wrong (totally possible!)

![image](https://github.com/user-attachments/assets/54f90625-139a-4aa9-af12-0cca9733e3a9)
![image](https://github.com/user-attachments/assets/335bd54a-e3b2-4be1-b0d1-da4b4943c066)
![image](https://github.com/user-attachments/assets/df4c0d48-9ab4-4250-84c6-42e49249f092)

and this is the `SuggestionProvider`:

```java
@Override
public @NotNull Collection<String> getSuggestions(final @NotNull ExecutionContext<BukkitCommandActor> context) {
    final StringStream input = context.input();
    // ...
    System.out.println("Position: " + input.position() + " /  Remaining: " + input.remaining());
    // ...
    return List.of("1 2 3");
}
```
`[12:38:00 INFO]: [LampTest] Position: 0 /  Remaining: 27` printed only once, despite me trying to type all arguments manually.

**Comment by Revxrsal** [comment]
Can you please try the latest beta? It introduces a new auto-completion system which is more robust and predictable than the previous one.

**Comment by Grabsky** [comment]
**@Revxrsal**
Works much better now, thanks for taking your time to fix this.

![image](https://github.com/user-attachments/assets/8dd6cdf6-32bb-4d00-86e8-223618172ce3)
