### ISSUE TITLE
Bug with command arguments containing special charaters with brigadier in minecraft 1.21

### ISSUE THREAD

**Issue by IbanEtchep** [Revxrsal/Lamp#120]
Hi, i get this error on arguments containing special charaters like `: / @ # à é ...` when brigadier is enabled.

![image](https://github.com/user-attachments/assets/1517e2c7-7bd6-4c78-8939-4f8e708875a3)

I'm currently on Lamp 3.3.2.

**Comment by Revxrsal** [comment]
Pretty sure that's [Brigadier's design](https://github.com/Mojang/brigadier/blob/master/src/main/java/com/mojang/brigadier/StringReader.java#L169-L175) by default?

Also, Lamp v3 is no longer maintained. Please update to v4.
