### ISSUE TITLE
Parent Command & Standalone Command simultaneously

### ISSUE THREAD

**Issue by Tofpu** [Revxrsal/Lamp#17]
Hey! Is it possible to have a command under a parent, and also be standalone simultaneously? If that doesn't make sense to you, here; let me show you a demonstration of the idea:
```java
@Command("parent")
public final class ExampleCommand {
    
    @Default // /parent
    public String defaultCommand() {
        return "default command";
    }
    
    @Subcommand("sub") // /parent sub
    public String subCommand() {
        return "sub command";
    }
    
    @Command("test") // /test
    @Subcommand("test") // /parent test
    public String subCommand2() {
        return "test command";
    }
}
```

If so, could you please show me how I could achieve such a thing? Thank you!

**Comment by Revxrsal** [comment]
I'm not sure if I understand the problem correctly, but I believe you can achieve this with annotating the class or method with @Command. When it has @Default, it'll automatically be classified as a category and other commands of the same parent will go under it with respecting @Default.

**Comment by Tofpu** [comment]
> I'm not sure if I understand the problem correctly, but I believe you can achieve this with annotating the class or method with @command. When it has @default, it'll automatically be classified as a category and other commands of the same parent will go under it with respecting @default.

Whoops, forgot to include the command annotation at the top of the class in my example. I tried what you suggested, and the command didn't work. Let me try to rephrase it again. 

I'll use a real-life example as it'll make more sense, previously with the Cloud framework; I had a `/sb` parent command, with the other commands being associated with it (such as `/sb join`, `/sb leave`, and `/sb score`), and also had the mentioned command also be independently available, without being required to mention the parent command (such as `/join`, `/leave`, and `/score`).

So my question is, is there an annotation that allows this? without having to create two separate classes that achieve what I mentioned above?

**Comment by Revxrsal** [comment]
That's a slightly odd use case, however `@Command` and `@Subcommand` both accept an array of strings. Since it fits you better to use `@Command` for that, you can do something like this:

```java
    @Command({"parent sub", "sub"}) // /test
    public String subCommand() {
        return "sub command";
    }
    
    @Command({"parent test", "test"}) // /test or /parent test
    public String subCommand2() {
        return "test command";
    }
```
Which is nothing too fancy, just giving the command multiple paths.

**Comment by Tofpu** [comment]
> That's a slightly odd use case, however `@Command` and `@Subcommand` both accept an array of strings. Since it fits you better to use `@Command` for that, you can do something like this:
> 
> ```java
>     @Command({"parent sub", "sub"}) // /sub or /parent sub
>     public String subCommand() {
>         return "sub command";
>     }
>     
>     @Command({"parent test", "test"}) // /test or /parent test
>     public String subCommand2() {
>         return "test command";
>     }
> ```
> 
> Which is nothing too fancy, just giving the command multiple paths.

For my reasoning, the commands I mentioned will mostly be used by the players, and it'd feel a bit more integrated into the server, however, the rest of the commands are already locked behind a permission node so it wouldn't really make a difference for the server administrators

Anyway, I tried both things you suggested: I assume I got some unintended effects?

When I used the Subcommand annotation: **(I presume that's intended, just wanted to mention it for the sake of it)**
```java
@Subcommand({"sb score", "score"})
```
The command became `/sb sb score`, and `/sb score`

When I used the Command annotation:
```java
@Command({"sb score", "score"})
```
The whole `/sb` commands returned the score, regardless of the input given (including invalid arguments); and `/score` wasn't also available

**Comment by Tofpu** [comment]
Yeah, I'll see you there then
