### ISSUE TITLE
Args in command (not at the ending)

### ISSUE THREAD

**Issue by wasn325** [Revxrsal/Lamp#28]
Hey, I've been playing with Lamp for a while and I am trying something, but I can't figure out how.

Is ist possible to set args at a specific position in the (sub)command?
Like "user \<name\> changePassword \<password\>" and not having all args at the end?

**Comment by Revxrsal** [comment]
Unfortunately not at the moment. It is required that all command paths be literals and arguments at the end. This is more idiomatic and easier to provide suggestions and validation for. Though this may be lifted in the future.

**Comment by wasn325** [comment]
ou ok, but thanks anyway :D
