### ISSUE TITLE
able to specify string as quoted, greedy, single?

### ISSUE THREAD

**Issue by portlek** [Revxrsal/Lamp#31]

**Comment by Revxrsal** [comment]
Strings are quoted by default. If it comes at the end of the command (i.e. the last parameter), it'll become greedy. You can annotate it anywhere with `@Single` to mark it as single.

It'll make no sense to mark a string as greedy when it's in the middle of the command, as following parameters will not get a place.

You can also register a custom ArgumentTypeResolver in BukkitBrigadier.

**Comment by portlek** [comment]
ye but i want to make something like /test xxx "quoutedParam" "quoutedParam". i want to able to mark string quoted whereever i want. i guess i'll change the default String resolver.
