### ISSUE TITLE
Set a description for a parent command.

### ISSUE THREAD

**Issue by DevCyntrix** [Revxrsal/Lamp#33]
Hi,

I create a command with subcommands with @Command, @SubCommand, @Default. 
Something like that

```java
@Command("test")
@Description("Description") // I tried here
public class TestCommand {

    @Default
    @Description("Description") // and here
    public void onRoot(BukkitCommandActor actor) {

    }

    @Subcommand("test reload")
    @CommandPermission("test.command.reload")
    public void onTest(BukkitCommandActor actor) {
        //plugin.onDisable();
        //plugin.onEnable();
        actor.reply(plugin.getPrefix() + "§cThe plugin has been reloaded successfully");
    }
}
```

But the description if I execute /help test didn't changed. It shows "test: " without an description. How can I change the plugin command description in the help page? Maybe someone can help me.

Best regards,
Ricardo

**Comment by Revxrsal** [comment]
Sorry, I forgot to reply here.
Unfortunately, command categories are not elements that can hold annotations. As in, a category is not necessarily bound to a method or a class, therefore there's no way to read a Description annotation on them.

Though this may be improved in the future, you can do something such as `plugin.getCommand("mycommand").setDescription("...")`
