### ISSUE TITLE
get missing permission from NoPermissionException handler

### ISSUE THREAD

**Issue by megagigakox** [Revxrsal/Lamp#35]
Hi, i have a question. Is it possible to get missing permission from NoPermissionException handler? if so how to do it?

my code:
        commandHandler.registerExceptionHandler(NoPermissionException.class, (actor, ex) -> {
            TextBuilder.builder()
                    .text("&7You dont have permission to execute this command! &7(&c{PERM}&7)")
                    .placeholder("{PERM}", I WANT TO GET MISSING PERMISSION HERE )
                    .send(((BukkitCommandActor) actor).getSender());
        });

**Comment by Revxrsal** [comment]
The permission is not necessarily a permission node (i.e. `my.command`), so there is no 100% guaranteed way to always get it. However, you may be able to do the following:
```java
CommandPermission permission = ex.getPermission();
if (permission instanceof BukkitCommandPermission) {
  org.bukkit.permissions.Permission bukkitPerm = ((BukkitCommandPermission) permission).getPermission();
  // do whatever you want here
} else {
   // not necessarily a BukkitCommandPermission. for example, a category's permission is determined by whether the actor has access to any of its subcommands, therefore no permission node is relevant here.
   // you can just send a "You don't have permission!", or instead list all permissions of its children.
}
```

**Comment by megagigakox** [comment]
> The permission is not necessarily a permission node (i.e. `my.command`), so there is no 100% guaranteed way to always get it. However, you may be able to do the following:
> 
> ```java
> CommandPermission permission = ex.getPermission();
> if (permission instanceof BukkitCommandPermission) {
>   org.bukkit.permissions.Permission bukkitPerm = ((BukkitCommandPermission) permission).getPermission();
>   // do whatever you want here
> } else {
>    // not necessarily a BukkitCommandPermission. for example, a category's permission is determined by whether the actor has access to any of its subcommands, therefore no permission node is relevant here.
>    // you can just send a "You don't have permission!", or instead list all permissions of its children.
> }
> ```

fine, thanks for response. I tried to test your code but this: if (permission instanceof BukkitCommandPermission) never execute.
