### ISSUE TITLE
default argument type resolvers do not make sense to me.

### ISSUE THREAD

**Issue by portlek** [Revxrsal/Lamp#36]
each default arg type bound like this:
![image](https://user-images.githubusercontent.com/12835420/203858581-61d1a7ff-20be-48f8-a4b0-244ce1a9b728.png)
but the type does not do anything at all in the bind method:
![image](https://user-images.githubusercontent.com/12835420/203858610-848d67d0-0717-4fb7-a4c5-f1bd0dd0d5fa.png)
and the parameter's class type hasn't check in the argument resolver too:
![image](https://user-images.githubusercontent.com/12835420/203858644-ba88a43d-b90b-4cd6-a8c3-ac306a726912.png)
and looks like it does support nullable too:
![image](https://user-images.githubusercontent.com/12835420/203858825-95bc402c-ba36-40ce-ae11-35104ae2f8aa.png)
so i've made the string resolver like this:
```java
public interface CommandFactory {
  @Inject
  @NotNull
  @Provides
  @Singleton
  static BukkitCommandHandler commandManager(@NotNull final Plugin plugin) {
    final var handler = BukkitCommandHandler.create(plugin);
    handler.registerBrigadier();
    handler.enableAdventure();
    handler
      .getBrigadier()
      .orElseThrow()
      .registerArgumentTypeResolver(
        0,
        parameter -> {
          if (parameter.getType() != String.class) {
            return null;
          }
          if (parameter.getType().isAnnotationPresent(Quoted.class)) {
            return StringArgumentType.string();
          }
          if (parameter.consumesAllString()) {
            return StringArgumentType.greedyString();
          }
          return StringArgumentType.word();
        }
      );
    return handler;
  }
}
```
am i wrong with the returning null if the parameter is not a string? because looks like if it does not find any resolver, returns string already so it should check the parameter type first.

**Comment by Revxrsal** [comment]
> am i wrong with the returning null if the parameter is not a string? because looks like if it does not find any resolver, returns string already so it should check the parameter type first.
Nope, null is perfectly valid to return and it means the resolver is not designed for that type of parameter, in which other resolvers will be tried instead.

I'll correct the behavior of #bind today if I get a chance. Thanks for the heads up!

**Comment by portlek** [comment]
then all default arg type resolvers should include type check then? like the number type resolver?

**Comment by Revxrsal** [comment]
Should be fixed in https://github.com/Revxrsal/Lamp/commit/5cbeef24b343e7ab7be73f819d5d27f1c053e971
