### ISSUE TITLE
[Enhancement] Auto Completion Configs

### ISSUE THREAD

**Issue by PoQuatre** [Revxrsal/Lamp#4]
Hi, I have been playing around with Lamp for a few days now, and the fact that Auto Completion Configs are missing, is quite limiting for my use cases (e.g. showing a list of player with a specific permission), as it would be unreasonnable to register a different `SuggestionProvider` for each variation.

### How it could be implemented
```java
@Command("example")
@AutoComplete("@completion:key1=value1,key2=42")
public void command(...) {
    ...
}
```

```java
commandHandler.getAutoCompleter().registerSuggestion("completion", (args, sender, command, configs) -> {
    if (configs.has("key1")) {
        String value = configs.getAsString("key1");
        ...
    } else if (configs.has("key2") {
        int value = configs.getAsInt("key2");
        ...
    }
}
```

**Comment by Revxrsal** [comment]
This will be implemented in the next update. Thank you for your suggestion.
