### ISSUE TITLE
feat: Flag and Switch aliases

### ISSUE THREAD

**Issue by GamerCoder215** [Revxrsal/Lamp#41]
Hello,

A neat suggestion I think would be nice for Lamp is the option for `@Flag` and `@Switch` annotations to support aliases.
I'm unsure if this is natively supported by brigadier since I've never worked with commands before, but it would be cool to use.

Perhaps the inputted array could override all of the names for the switch/flag, or add on upon the inputted parameter name (that could be an option in the CommandHandler).
The [original message](https://discord.com/channels/939962855476846614/939963749496946778/1057026496323129386) is available on the Lamp Discord.

Something like this:
```java
public void send(Player sender, @Flag({"sendtype", "sendingtype", "st"}) SendType type, @Switch({"broadcast", "sendall"}) boolean sendAll) {
   // ...
}
```

@SkytAsul (their [original message](https://discord.com/channels/939962855476846614/939963749496946778/1057027032002859008)) also recommended the option to mix flags and/or switches together, as in some Unix commands, such as:
```bash
rm -r -f
# Becomes...
rm -rf
```

Thanks!

**Comment by Revxrsal** [comment]
Thank you for the suggestion. This is planned, but I can't give any promises when it will be ready. I'll leave the issue open in the meantime.

**Comment by GamerCoder215** [comment]
Any updates on this?

**Comment by Revxrsal** [comment]
To be honest, I'm not sure if this would align well with the overall (strict) design of Lamp. This would easily mess up command completions and make the process of finding commands a lot harder. Also, considering the fact that Lamp attempts to 100% incorporate with Brigadier, this wouldn't work as Brigadier doesn't have the idea of flags and switches, and attempts to bypass that would lead to undesired results (e.g. having to see all possible outputs at once, -r, -rf, -f, -r -f even though you wouldn't need them)

Unfortunately, Lamp wasn't built on the convention of Unix commands, rather Minecraft ones, which may require a shift in mindset when using it.
