### ISSUE TITLE
Fix wiki Page with changes according to v3.1.2

### ISSUE THREAD

**Issue by GamerCoder215** [Revxrsal/Lamp#42]
Hello,
I noticed that you forgot to update the [Lamp wiki](https://github.com/Revxrsal/Lamp/wiki) with changes reflected in v3.1.2.

The first and third examples [here](https://github.com/Revxrsal/Lamp/wiki), the second and fourth example [here](https://github.com/Revxrsal/Lamp/wiki/Building-commands#zip-file-commands), the second example [here](https://github.com/Revxrsal/Lamp/wiki/Command-help#example), the third example [here](https://github.com/Revxrsal/Lamp/wiki/Auto-completions-and-suggestions#completions-by-parameter-type) and the second and third example [here](https://github.com/Revxrsal/Lamp/wiki/Auto-completions-and-suggestions#completions-by-autocomplete) use the old `@Default` functionality.

I would also recommend creating a wiki page explaining `@DefaultFor` if you haven't done so already.

Thanks 😄

**Comment by Revxrsal** [comment]
Thank you for bringing this to my notice. As I haven't fully decided on the future of `@Default`, I'll leave them for now.
