### ISSUE TITLE
`@DefaultFor` requires fixing / `@Default` in v3.1.2 doesn't work properly

### ISSUE THREAD

**Issue by GamerCoder215** [Revxrsal/Lamp#46]
Hello,

As described here. the `@DefaultFor` annotation requires additional polishing and fixing in `v3.1.2`.

My final code being as follows:
```java
        @Default
        public void corporationInfoDefault(Player p) { corporationInfo(p); }

        @Subcommand("info")
        public void corporationInfo(Player p) {
            wrapper.corporationInfo(p);
            NovaSound.ENTITY_ARROW_HIT_PLAYER.playSuccess(p);
        }
```

As shown [here](https://discord.com/channels/939962855476846614/939963749496946778/1069314996120584285), firstly, the annotation does not allow sub-commands with command aliases correctly:

![image](https://user-images.githubusercontent.com/54124162/216713916-464992de-221f-4a82-8565-303d0d3e4825.png)
![image](https://user-images.githubusercontent.com/54124162/216713956-c53a1428-bf97-4892-8c62-2b232cb3fa9c.png)

Secondly, when reverting back to the deprecated `@Default` command, sub-commands fail entirely:

![image](https://user-images.githubusercontent.com/54124162/216714055-e32306ce-234b-4451-bb0f-b525fc24d8da.png)

I've downgraded to v3.1.1 until @Revxrsal has gotten back and fixed these issues in the next version.
Thanks

**Comment by GamerCoder215** [comment]
Errors are also available in #44

**Comment by Revxrsal** [comment]
Should be fixed in https://github.com/Revxrsal/Lamp/commit/a8cc932f69ba9943f9fb92193deb8fba009e4db5. Thanks for reporting!

**Comment by GamerCoder215** [comment]
Default works ok for both command roots & aliases, but no sub-commands work at all...

My Code:
```java
    @Command({"business", "nbusiness", "nb", "b"})
    @Description("Manage your Novaconomy Business")
    @Usage("/business <create|info|delete|addproduct|stock|query|...> <args...>")
    private static final class BusinessCommands {

        private final CommandWrapperV2 wrapper;

        private BusinessCommands(CommandWrapperV2 wrapper) {
            this.wrapper = wrapper;

            handler.register(this);
        }

        @DefaultFor("business")
        public void businessInfoDefault(Player p) { businessInfo(p); }

        @Subcommand({"info", "information"})
        public void businessInfo(Player p) { wrapper.businessInfo(p); }

}
```
![image](https://user-images.githubusercontent.com/54124162/216828778-2c7c3c06-96c0-416f-a1f8-7d0ab3caa070.png)

Also, for sub-commands of sub-commands, like this:
```java
        @Subcommand({"keyword", "keywords"})
        @DefaultFor("business keyword")
        @CommandPermission("novaconomy.user.business.keywords")
        public void keywords(Player p) {
            wrapper.listKeywords(p);
        }

        @Subcommand({"keyword list", "keywords list", "keyword l", "keywords l"})
        @CommandPermission("novaconomy.user.business.keywords")
        public void keywordsList(Player p) { wrapper.listKeywords(p); }

        @Subcommand({"keywords add", "keyword add"})
        @CommandPermission("novaconomy.user.business.keywords")
        public void addKeywords(Player p, String keywords) {
            wrapper.addKeywords(p, keywords.split("[ ,]"));
        }
```

Is `@DefaultFor` being used correctly?

**Comment by Revxrsal** [comment]
Can I see your code where you create the command handler and register all the commands?

**Comment by GamerCoder215** [comment]
Update:

After adding all of the aliases like this:

```java
@DefaultFor({"business", "nbusiness", "b", "nb"})
```

The aliases should work.
In order to avoid future confusion for anyone, you should probably:
- Mention this in the javadocs and/or throw if not aliases are added
- Make it so that the annotation automatically adds it for its aliases

**Comment by Revxrsal** [comment]
v3.1.3 contains fixes, please let me know if the bug persists.

**Comment by Revxrsal** [comment]
I'll consider this fixed. Thanks for the help!
