### ISSUE TITLE
Example Plugin for Reference.

### ISSUE THREAD

**Issue by davidegrigioni** [Revxrsal/Lamp#51]
As I tried to look multiple times into how could I register the handler and in general to have something to refer to I decided to make an Example Plugin.
As it is my first time doing something like that I'll leave the link, If someone can help me in maybe making a pull request it would be nice

[https://github.com/davidegrigioni/ExampleLampPlugin](url)

**Comment by Revxrsal** [comment]
o/
There is indeed a full example at https://github.com/Revxrsal/Lamp/tree/examples. It's a bit old, but the code remains (mostly) the same nonetheless. I'll update it soon. But for now it should give you a solid idea on using Lamp
