### ISSUE TITLE
"pluginname:command" is considered invalid

### ISSUE THREAD

**Issue by raffel080108** [Revxrsal/Lamp#52]
Let's say, for example, I register the command "test" in my plugin "testplugin".
I can now use the command "/test" and everything works fine.
However, if I try to type "/testplugin:test", it even shows up in auto-completion, but when executed it states "Invalid command: testplugin:test" (Just in plain text, not as brigadier error or something like that).

So the command seems to get registered correctly even in the mentioned form, but it is still considered invalid in some way

An example from a current project of mine:
![image](https://user-images.githubusercontent.com/62069283/225977722-7feb1b8a-ad9e-4eb5-a9e6-9b376a2b7fbf.png)
![image](https://user-images.githubusercontent.com/62069283/225978251-967f0eea-2011-46bf-bb2c-462cdbc055b3.png)
![image](https://user-images.githubusercontent.com/62069283/225977663-26c6a8e2-1a6e-4046-b47a-ce9a59659f70.png)
_(Just "/checktarget" works fine in this case)_

**Comment by raffel080108** [comment]
I have also noticed, that the auto-completion for the mentioned form of a command is displayed to a player even if they do not have the specified command permission, in oppose to the normal format, which is completely hidden in that case

**Comment by Revxrsal** [comment]
That's indeed a bug. I'll look into it when I get a chance. Thanks for the notice.

**Comment by Revxrsal** [comment]
Seems to be fixed in https://github.com/Revxrsal/Lamp/commit/c54fcfbcb9139fcccb8f5bb3f0e3f49bcaf66901. Thanks for the report!
