### ISSUE TITLE
@Optional or @Default not working correctly together @Flag

### ISSUE THREAD

**Issue by bivashy** [Revxrsal/Lamp#56]
When we are defining @Optional and @Flag at the same time, value of parameter will be <?null>
Example command:
```java
@Command("test")
public class TestCommand {
    @DefaultFor("test")
    public void onDefault(String first, @Flag("second") @Optional String second) {
        System.out.println(first);
        System.out.println(second);
    }
}
```

When we execute `/test 1` It`ll print out:
```
1
<?null>
```

(Second value is plain String)

**Comment by Revxrsal** [comment]
Fixed in https://github.com/Revxrsal/Lamp/commit/15212537897c3f68ba394711059dff2e4fddb94b
