### ISSUE TITLE
Fabric

### ISSUE THREAD

**Issue by creatorfromhell** [Revxrsal/Lamp#59]
Hello,

 I was looking over this project, which is really awesome, and was wondering if the Brigadier module allows for Fabric MC support.
 
 Thanks in advance,

**Comment by Revxrsal** [comment]
o/
The brigadier module is pretty bare-bones and generic, and does not allow for richer features that are platform-native. While it should work anywhere that uses Brigadier (providing you provide a LampBrigadier implementation), Fabric may benefit from having its own module in the future.

**Comment by creatorfromhell** [comment]
> o/ The brigadier module is pretty bare-bones and generic, and does not allow for richer features that are platform-native. While it should work anywhere that uses Brigadier (providing you provide a LampBrigadier implementation), Fabric may benefit from having its own module in the future.

That would be awesome.

**Comment by creatorfromhell** [comment]
This should pend v4.

**Comment by Revxrsal** [comment]
Implemented in https://github.com/Revxrsal/Lamp/commit/cf67dbde550c4f5858196c4e97fa55c61d3c214d.
