### ISSUE TITLE
Parent commands do not allow non-subcommand overload

### ISSUE THREAD

**Issue by MaowImpl** [Revxrsal/Lamp#6]
i.e. if I have the following commands:
```
mycom
mycom list
mycom add
```
The only command that shows up is `mycom`.
(Each is its own method, and the path is specified in full via `@Command`)
I am currently working on a plugin that would benefit from this functionality, so it would be best if Lamp supported it.

**Comment by alisson0022** [comment]
Can you show a snippet of your code?

**Comment by MaowImpl** [comment]
It went something like...
```java
@Command("mycom")
public void onMyCom() {}

@Command("mycom list")
public void onList() {}
```

**Comment by Revxrsal** [comment]
Your "mycom" is being parsed as an action command, so any parameters will be parsed for it and not other commands.

Solution: add @Default to "mycom"
