### ISSUE TITLE
Minestom Command Support.

### ISSUE THREAD

**Issue by creatorfromhell** [Revxrsal/Lamp#60]
Fairly self-explanatory, but support for the Minestom Software.
https://github.com/Minestom/Minestom

**Comment by Revxrsal** [comment]
I'll leave this issue open in case any progress is made here.

**Comment by Revxrsal** [comment]
Implemented in https://github.com/Revxrsal/Lamp/commit/50463c138e3cab419ad579ef47fbcd3185266abb. Looks stable and usable for me, though it may need more thorough testing, as I have little experience in Minestom and can't go through the trouble of recreating a Minecraft server from scratch 😅

Should you encounter any issues, please open separate issues (or PRs) to simplify tracking them.
