### ISSUE TITLE
Custom exception when @Flag value is not specified

### ISSUE THREAD

**Issue by U61vashka** [Revxrsal/Lamp#7]
When we don't specify a flag value, an IndexOutOfBoundsException is thrown.

Can we have custom exception (For example FlagValueNotAssignedException) for this moment?

Command: **test flag -test**

Code:
```
import revxrsal.commands.annotation.Command;
import revxrsal.commands.annotation.Flag;
import revxrsal.commands.annotation.Subcommand;

@Command("test")
public class TestCommand {
	
	@Subcommand("flag")
	public void onDefault(@Flag("test") String test) {
		
	}
	
}
```

Stacktrace:
<p><code>java.lang.IndexOutOfBoundsException: Index: 0, Size: 0</code><br /><code>&nbsp; at java.util.LinkedList.checkElementIndex(Unknown Source)</code><br /><code>&nbsp; at java.util.LinkedList.remove(Unknown Source)</code><br /><code>&nbsp; at revxrsal.commands.core.BaseCommandDispatcher.handleFlag(<a href="https://github.com/Revxrsal/Lamp/blob/master/common/src/main/java/revxrsal/commands/core/BaseCommandDispatcher.java#L186">BaseCommandDispatcher.java:186</a>)</code><br /><code>&nbsp; at revxrsal.commands.core.BaseCommandDispatcher.getMethodArguments(<a href="https://github.com/Revxrsal/Lamp/blob/master/common/src/main/java/revxrsal/commands/core/BaseCommandDispatcher.java#L105">BaseCommandDispatcher.java:105</a>)</code><br /><code>&nbsp; at revxrsal.commands.core.BaseCommandDispatcher.execute(<a href="https://github.com/Revxrsal/Lamp/blob/master/common/src/main/java/revxrsal/commands/core/BaseCommandDispatcher.java#L82">BaseCommandDispatcher.java:82</a>)</code><br /><code>&nbsp; at revxrsal.commands.core.BaseCommandDispatcher.searchCategory(<a href="https://github.com/Revxrsal/Lamp/blob/master/common/src/main/java/revxrsal/commands/core/BaseCommandDispatcher.java#L61">BaseCommandDispatcher.java:61</a>)</code><br /><code>&nbsp; at revxrsal.commands.core.BaseCommandDispatcher.eval(<a href="https://github.com/Revxrsal/Lamp/blob/master/common/src/main/java/revxrsal/commands/core/BaseCommandDispatcher.java#L44">BaseCommandDispatcher.java:44</a>)</code><br /><code>&nbsp; at revxrsal.commands.core.BaseCommandHandler.dispatch(<a href="https://github.com/Revxrsal/Lamp/blob/master/common/src/main/java/revxrsal/commands/core/BaseCommandHandler.java#L440">BaseCommandHandler.java:440</a>)</code></p>

**Comment by Revxrsal** [comment]
That sounds like a bug, it should throw a MissingArgumentException. Will try to get to this ASAP. Thank you

**Comment by Revxrsal** [comment]
Fixed in https://github.com/Revxrsal/Lamp/commit/9b5f5dae2abb8e5cc9b501e506e96998f4ed5119.
