### ISSUE TITLE
commandError Kotlin DSL removing apostrophes

### ISSUE THREAD

**Issue by joshbker** [Revxrsal/Lamp#72]
When using the `commandError` method to return in a command, the message sent in Minecraft chat does not contain any of the apostrophes that are in the code.

**Comment by Revxrsal** [comment]
Apologies for the late reply. `commandError`, just like all other exceptions and implementations of `CommandActor#xxxLocalized`, use Java's `MessageFormat` syntax. To use quotes, you have to escape them by using double single-quotes`''`
