### ISSUE TITLE
EntitySelector not sending tabcompletion

### ISSUE THREAD

**Issue by xaanndeer** [Revxrsal/Lamp#73]
Earlier today I updated Lamp from 3.1.5 to the latest commit (b61c1dd8d1) to fix the "Unknown command issue". After some testing I found out that the EntitySelector no longer sends tabcompletions.

**Comment by Revxrsal** [comment]
Yes, I've noticed this as well. It's a result of calling `CommandRegisteredEvent#setRawCommand(true)`. `setRawCommand` seems to fix many issues, but cause others. I still have to find a way to fix that.

**Comment by Revxrsal** [comment]
Fixed in 3.1.6. Thanks for the report.
