### ISSUE TITLE
command error if there's a colon in a string argument

### ISSUE THREAD

**Issue by nkomarn** [Revxrsal/Lamp#74]
After upgrading my server to Lamp https://github.com/Revxrsal/Lamp/commit/3c22956096618cc8247e540c50568332ffd99968 (from Lamp 3.1.3), I noticed one of my commands, that frequently takes inputs with multiple colons in it, no longer works.

Here's the source of the offending command, as well as examples of before (working) and after (broken since upgrading):
![image](https://github.com/Revxrsal/Lamp/assets/22900187/291937f8-5a96-4173-9343-ac7d8ac822f2)
![image](https://github.com/Revxrsal/Lamp/assets/22900187/420cf82e-0561-4b96-bc54-5c4b76a11539)
![image](https://github.com/Revxrsal/Lamp/assets/22900187/f5a6f9f5-4742-4487-b467-99528a849d20)

I haven't found a way to fix this on my end as of yet.

**Comment by GamerCoder215** [comment]
+1 reporting the same thing.

**Comment by Revxrsal** [comment]
I see. This must have to do with the name space stripping (Strings#stripNamespace). I'll see when I get the chance

**Comment by Revxrsal** [comment]
This should have been fixed in https://github.com/Revxrsal/Lamp/commit/98d75dc7ecfd8b2c1b2b61ce806c6a33b22cf7f9. Thanks for the report
