### ISSUE TITLE
Buffer Overrun When Ending Command With "\"

### ISSUE THREAD

**Issue by DoudGeorges** [Revxrsal/Lamp#79]
## Description
When ending any command with a backslash `\` while using Lamp as my command framework, an `ArgumentParseException` is thrown with a message indicating a buffer overrun while parsing arguments.

## Environment
- Server: Paper 1.20.4
- Lamp Version: 3.1.8

## Steps to Reproduce
1. Execute a command that ends with a backslash `\`.
2. Observe the error in the server console.

## Expected Behavior
Commands ending with a backslash should be processed without causing any errors.

## Actual Behavior
An error is thrown in the console with the following stack trace: https://gist.github.com/DoudGeorges/a599c49d3247d0e140ed5a6e1cde2c79

**Comment by Revxrsal** [comment]
Good catch, this bug has already been reported, but I forgot to patch it. Thanks for reporting.
