### ISSUE TITLE
Error when executing a command through the console.

### ISSUE THREAD

**Issue by JasperTheMinecraftDev** [Revxrsal/Lamp#80]
Hey! I've spotted an issue in Lamp. When a command is executed as the console, Lamp throws the following error: https://pastebin.com/yiHf2Ktw

Thanks for the awesome lib and I hope that you can solve it 🙂

**Comment by Revxrsal** [comment]
Pastebin doesn't seem to be working, but I assume the bug has been fixed. Please feel free to re-open the issue in case it wasn't.
