### ISSUE TITLE
Weird issue when single '/' was inputed

### ISSUE THREAD

**Issue by Longtianmu** [Revxrsal/Lamp#83]
As the pastebin.
https://paste.gg/p/anonymous/2739a50742794b97b85d18f7401abcd0

**Comment by Wector11211** [comment]
Duplicate #82

**Comment by Revxrsal** [comment]
What version of Lamp are you using? This should have been fixed in 3.1.9

**Comment by Longtianmu** [comment]
I'm still using 3.1.8 though
I will try to bump the version and test it later
