### ISSUE TITLE
Entity Selector Issue

### ISSUE THREAD

**Issue by FigT** [Revxrsal/Lamp#90]
## Description
I'm trying to disable `@` entity selectors in commands for users without permission. This works for tab auto-complete, however, it doesn't prevent their usage. 
I tried to make a custom Player value resolver to prevent this, but found the resolvers stack, and cannot be replaced.

## Scenario
I have a simple message command, however, with the entity selectors it can be abused to find the nearest player, among other things. As shown the tab complete works fine, but the entity selectors can still be used,
<br/>
*(screenshot without permissions)*
<img width="505" alt="Screenshot 2024-03-28 at 4 00 12 PM" src="https://github.com/Revxrsal/Lamp/assets/22107750/a91d6fe0-cad9-4217-bc03-aa18c81c7580">
*(screenshot with op)*
<img width="369" alt="Screenshot 2024-03-28 at 4 01 51 PM" src="https://github.com/Revxrsal/Lamp/assets/22107750/472e66e4-d4d7-4ff8-bfd0-146422c99e76">

## Conclusion
What's the best way to go about this? Ability to replace value resolvers? A method to disable entity selectors? I'm willing to submit a PR, just wanting your thoughts on the best path forward. :)

**Comment by Revxrsal** [comment]
You can disable this feature by calling `BukkitBrigadier.disableNativePlayerCompletions()`. So something like this:
```java
commandHandler.getBrigadier().ifPresent(brigadier -> {
	brigadier.disableNativePlayerCompletions();
	brigadier.register();
});
```

Do note that the [default `Player` resolver](https://github.com/Revxrsal/Lamp/blob/master/bukkit/src/main/java/revxrsal/commands/bukkit/core/BukkitHandler.java#L73) also has basic support for selectors too. You can overwrite it with something like:
```java
// 															vvv priority/order in stack
commandHandler.registerValueResolver(0, Player.class, context -> { ... });
```

**Comment by FigT** [comment]
> ```java
> commandHandler.getBrigadier().ifPresent(brigadier -> {
> 	brigadier.disableNativePlayerCompletions();
> 	brigadier.register();
> });
> ```

I see, I didn't realize this was a method. 

But, as you mentioned the default Player resolver still has some support for selectors, so following your example, I tried to disable that, however, this seems to break the sender resolver, causing *all* `Player`  arguments needing to be provided. I tried circumventing this by checking if the argument is equal to an arbitrary string (`self`) and using the `@Default` annotation, however, this is clunky and still allows you to specify a player, and autocompletes. Code snippets and screenshot below.

<br/>

*registration:*
```java
this.commandHandler.registerValueResolver(0, Player.class, context -> {
    String name = context.pop();

    if (name.equalsIgnoreCase("self")) {
        return ((BukkitCommandActor) context.actor()).requirePlayer();
    }

    Player player = Bukkit.getPlayer(name);

    if (player == null) {
        throw new CommandErrorException("Player not found: '" + name + "'");
    }

    return player;
});

this.commandHandler.register(...);

this.commandHandler.getBrigadier().ifPresent(brigadier -> {
    brigadier.disableNativePlayerCompletion();
    brigadier.register();
});
```

*command:*
```java
    @Command("test")
    private void handleMsgTest(@Default("self") Player player) {
        player.sendMessage("This is a test, " + player.getName());
    }
```
*in-game:*
<img width="342" src="https://github.com/Revxrsal/Lamp/assets/22107750/b79b3799-d944-4b30-8f33-131686f4ef42">

**Comment by FigT** [comment]
@Revxrsal just bumping this in case you didn’t see

**Comment by Revxrsal** [comment]
Sender resolver has zero priority, setting the priority to 1 should work.
