### ISSUE TITLE
Unregister default minecraft command 

### ISSUE THREAD

**Issue by EURedBoy** [Revxrsal/Lamp#91]
I'm trying to unregister a default minecraft command `/stats` to replace it with mine but it doesn't seems to work
![image](https://github.com/Revxrsal/Lamp/assets/69308679/fe8c1c92-cf12-4ac9-a3a6-d56cb3427388)

**Comment by Revxrsal** [comment]
`handler.unregister` is for commands created by the CommandHandler only. If you want to remove the command, you may need to use reflection to unregister it on the vanilla CommandDispatcher
