### ISSUE TITLE
Literals at any given position

### ISSUE THREAD

**Issue by Fulminazzo** [Revxrsal/Lamp#95]
I'm interested in having literals in the middle of arguments, so that it is possible to create commands like:
`/team <team> invite <player>`
`/permission <player> set <permission>`

I know this question has been already answered, but it has been quite a while and I was wondering if there are any progresses or future plans for the matter.

**Comment by Revxrsal** [comment]
Sadly not quite yet. There have been _some_ work in the `dynamic-parameters` branch, though honestly it's a bit abandoned and has some bugs.

The de-facto way for this, is to use enums. You can also annotate it with `@LiteralEnum` to make it appear like a native command on Brigadier:
```java

public enum TeamAction {
	INVITE,
	...;
}


@Command("team")
public void teamCommand(Player sender, Team team, @LiteralEnum TeamAction action, ArgumentStack args (or Player, etc.)) {
	switch (action) {
		case INVITE: ...
	}
}```
However you'll lose lots of the nice features that come with Lamp. I don't recommend this way.

Instead, just stick to having all your parameters come in succession. I don't see any reason why this is necessarily bad. With Brigadier and tab completions, it should be easy for users to understand it.
