### ISSUE TITLE
Cannot have commands with '/' characters.

### ISSUE THREAD

**Issue by HyperSkys** [Revxrsal/Lamp#96]
I was attempting to make a plugin similar to world edit but when trying to make a command like //set it wouldn't do anything but when I ran it said Invalid Command.

**Comment by Revxrsal** [comment]
I see. Was this with Brigadier enabled?

**Comment by HyperSkys** [comment]
Yeah it was with Brigadier enabled.

**Comment by HyperSkys** [comment]
Does seem like it is an issue with Brigadier, just checked with it disabled and it worked just fine.

**Comment by Revxrsal** [comment]
I assume [this line](https://github.com/Revxrsal/Lamp/blob/master/bukkit/src/main/java/revxrsal/commands/bukkit/brigadier/NodeParser.java#L211) is the cause. Might need to double-check to see if `input` would even start with a `/` in normal commands or not. PR anyone?

**Comment by HyperSkys** [comment]
> I assume [this line](https://github.com/Revxrsal/Lamp/blob/master/bukkit/src/main/java/revxrsal/commands/bukkit/brigadier/NodeParser.java#L211) is the cause. Might need to double-check to see if `input` would even start with a `/` in normal commands or not. PR anyone?

Seems like it is, you must've added a safety check out of instinct just incase someone thought it worked like you had to put a slash before it for a command.

**Comment by HyperSkys** [comment]
> I assume [this line](https://github.com/Revxrsal/Lamp/blob/master/bukkit/src/main/java/revxrsal/commands/bukkit/brigadier/NodeParser.java#L211) is the cause. Might need to double-check to see if `input` would even start with a `/` in normal commands or not. PR anyone?

Never mind that didn't do a thing the issue still happens.

**Comment by HyperSkys** [comment]
> I assume [this line](https://github.com/Revxrsal/Lamp/blob/master/bukkit/src/main/java/revxrsal/commands/bukkit/brigadier/NodeParser.java#L211) is the cause. Might need to double-check to see if `input` would even start with a `/` in normal commands or not. PR anyone?

Found the issue in the eval method in class BaseCommandDispatcher.java it throws the exception because the base command category could not be found.
